'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CalendarDays, MoreHorizontal, Plus, ArrowLeft } from 'lucide-react';
import { useParams } from 'next/navigation';
import { Sidebar } from '../../../components/Sidebar';
import { useApp } from '../../../components/AppProvider';
import { getProject,getTasks } from '../../../lib/api';
import { Project,Task } from '../../../lib/types';
import { Avatar } from '../../../components/Avatar';
const fallback:Project={id:'p1',name:'Design Homepage',description:'Homepage design and delivery',priority:'high',dueDate:'2026-09-12'};
export default function ProjectDetail(){const{user,loading}=useApp();const{id}=useParams<{id:string}>();const[sidebar,setSidebar]=useState(false);const[project,setProject]=useState<Project|null>(null);const[tasks,setTasks]=useState<Task[]>([]);useEffect(()=>{if(user&&id){getProject(id).then(setProject).catch(()=>setProject(fallback));getTasks(`projectId=${id}`).then(setTasks).catch(()=>setTasks([]))}},[user,id]);if(loading||!user)return <div className="min-h-screen flex items-center justify-center">Loading…</div>;if(!project)return null;const groups:[string,Task['status']][]=[['To Do','todo'],['Doing','doing'],['Completed','completed']];return <div className="app-shell flex"><Sidebar open={sidebar} onClose={()=>setSidebar(false)}/><main className="flex-1 min-w-0"><div className="topbar"><button className="icon-btn" onClick={()=>setSidebar(true)}><ArrowLeft size={13}/></button><div className="text-[10px] muted">Projects</div><span className="text-[10px] muted">›</span><div className="text-[10px] font-medium">{project.name}</div><div className="ml-auto"><button className="primary-btn flex items-center gap-1"><Plus size={12}/>Add Task</button></div></div><div className="workspace-wrap"><div className="mb-4"><h1 className="page-title">Tasks</h1><p className="text-[9px] muted mt-1">{project.description}</p></div><div className="list-sections">{groups.map(([label,status])=>{const items=tasks.filter(t=>t.status===status);return <section key={status}><div className="section-title"><span>⌄</span>{label}</div><div className="table-card"><div className="table-row table-head"><span>Task</span><span>Priority</span><span>Members</span><span>Due Date</span><span>Actions</span></div>{items.map(t=><div key={t.id} className="table-row"><Link href={`/tasks/${t.id}`} className="hover:underline">{t.title}</Link><span className={`priority p-${t.priority}`}>▴ {t.priority}</span><span><Avatar size="xs" name={t.team||'Dexter'}/></span><span>{t.dueDate?<><CalendarDays size={10} className="inline mr-1"/>{new Date(t.dueDate).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</>:'—'}</span><MoreHorizontal size={13} className="muted"/></div>)}<button className="add-inline">+ Add Task</button></div></section>})}</div></div></main></div>}
