'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Pencil, Sun, Palette, UserCircle2 } from 'lucide-react';
import { useApp } from '../../../components/AppProvider';
import { Avatar } from '../../../components/Avatar';
const accents=[['amber','#d97706'],['blue','#2563eb'],['pink','#db2777'],['rose','#e11d48'],['emerald','#059669'],['black','#111111']] as const;
export default function ProfileSettings(){const{user,theme,setTheme,accent,setAccent,logout}=useApp();const[panel,setPanel]=useState<'theme'|'color'|null>(null);if(!user)return <div className="min-h-screen flex items-center justify-center">Please login first.</div>;return <main className="min-h-screen bg-[var(--background)]"><div className="settings-shell"><aside className="settings-nav"><Link href="/" className="back-link"><ArrowLeft size={12}/>Back to app</Link><div className="settings-items"><button className="settings-item active"><UserCircle2 size={12}/>Profile</button><button onClick={()=>setPanel(panel==='theme'?null:'theme')} className="settings-item"><Sun size={12}/>Theme<ChevronRight size={11} className="ml-auto"/></button><button onClick={()=>setPanel(panel==='color'?null:'color')} className="settings-item"><Palette size={12}/>Color<ChevronRight size={11} className="ml-auto"/></button><button onClick={logout} className="settings-item text-rose-500">Log out</button></div></aside><section className="settings-main"><div className="settings-content"><h1 className="text-[15px] font-semibold">Profile</h1><div className="card mt-4 overflow-hidden"><div className="profile-row"><span>Profile picture</span><Avatar size="md" name={user.name}/></div><Row label="Email" value={user.email} editable/><Row label="Full name" value={user.name}/><Row label="Title" hint="Your job title or role" value={user.title}/><Row label="Username" hint="One word, like a nickname or first name" value={user.name.toLowerCase().replace(/\s+/g,'')}/></div><div className="card mt-5 p-4 flex items-center justify-between"><div><div className="text-[11px] font-semibold">Workspace access</div><div className="text-[9px] muted mt-1">Remove yourself from the workspace</div></div><button onClick={logout} className="text-[9px] bg-rose-50 text-rose-500 rounded px-3 py-2">Leave Workspace</button></div></div>{panel==='theme'&&<div className="settings-pop"><div className="muted text-[9px] px-2 pb-1">Theme</div><button className="menu-row" onClick={()=>setTheme('light')}>☼ Light {theme==='light'&&<Check size={11}/>}</button><button className="menu-row" onClick={()=>setTheme('dark')}>☾ Dark {theme==='dark'&&<Check size={11}/>}</button></div>}{panel==='color'&&<div className="settings-pop"><div className="muted text-[9px] px-2 pb-1">Color mode</div>{accents.map(([name,val])=><button className="menu-row" key={name} onClick={()=>setAccent(name)}><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-sm" style={{background:val}}/>{name[0].toUpperCase()+name.slice(1)}</span>{accent===name&&<Check size={11}/>}</button>)}</div>}</section></div></main>}
function Row({label,hint,value,editable}:{label:string;hint?:string;value:string;editable?:boolean}){return <div className="profile-field"><div><div className="text-[10px]">{label}</div>{hint&&<div className="text-[8px] muted mt-1">{hint}</div>}</div><div className="flex items-center gap-2"><span className={`text-[10px] ${editable?'':'px-2 py-1 bg-[var(--muted-surface)] rounded'}`}>{value}</span>{editable&&<Pencil size={10} className="muted"/>}</div></div>}
