'use client';
import { useEffect, useMemo, useState } from 'react';
import { Plus, Search, SlidersHorizontal, MoreHorizontal, Check, ChevronRight } from 'lucide-react';
import { Sidebar } from '../../components/Sidebar';
import { useApp } from '../../components/AppProvider';
import { getProjects } from '../../lib/api';
import { Project } from '../../lib/types';
import Link from 'next/link';
import { Avatar } from '../../components/Avatar';
const fallback:Project[]=[{id:'p1',name:'Design Homepage',description:'Homepage design and delivery',priority:'high',dueDate:'2026-09-12'},{id:'p2',name:'Develop Login Feature',description:'Authentication implementation',priority:'low',dueDate:'2026-09-15'},{id:'p3',name:'Test Payment Gateway',description:'Payment integration testing',priority:'medium',dueDate:'2026-09-18'}];
export default function Projects(){const{user,loading}=useApp();const[sidebar,setSidebar]=useState(false);const[projects,setProjects]=useState<Project[]>([]);const[search,setSearch]=useState('');const[filterOpen,setFilterOpen]=useState(false);const[priority,setPriority]=useState<string|null>(null);useEffect(()=>{if(user)getProjects().then(setProjects).catch(()=>setProjects(fallback))},[user]);const list=useMemo(()=>projects.filter(p=>(!search||p.name.toLowerCase().includes(search.toLowerCase()))&&(!priority||p.priority===priority)),[projects,search,priority]);if(loading||!user)return <div className="min-h-screen flex items-center justify-center">Loading…</div>;return <div className="app-shell flex"><Sidebar open={sidebar} onClose={()=>setSidebar(false)}/><main className="flex-1 min-w-0"><div className="topbar"><button className="icon-btn md:hidden" onClick={()=>setSidebar(true)}>☰</button><h1 className="text-[13px] font-semibold ml-1">Projects</h1><div className="ml-auto flex items-center gap-1.5"><label className="searchbox"><Search size={13}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/></label><button className="icon-btn"><span className="text-[10px]">▦</span></button><button className="icon-btn relative" onClick={()=>setFilterOpen(v=>!v)}><SlidersHorizontal size={14}/></button><button className="primary-btn flex items-center gap-1"><Plus size={12}/>Add Project</button></div></div><div className="workspace-wrap"><div className="relative">{filterOpen&&<div className="popover filter-pop" style={{right:75,top:0}}><div className="w-36 p-1">{['Status','Priority','Members','Due Date','Teams','Labels','Reporter'].map(x=><button className="menu-row" key={x}><span>{x}</span><ChevronRight size={11}/></button>)}</div><div className="w-28 border-l border-[var(--border)] p-1"><button className="menu-row" onClick={()=>{setPriority(null);setFilterOpen(false)}}>All <Check size={11}/></button>{['urgent','high','medium','low'].map(x=><button key={x} className="menu-row" onClick={()=>{setPriority(x);setFilterOpen(false)}}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div></div>}
<div className="table-card"><div className="table-row table-head"><span>Projects</span><span>Priority</span><span>Lead</span><span>Due Date</span><span>Actions</span></div>{list.map(p=><div className="table-row" key={p.id}><Link href={`/projects/${p.id}`} className="hover:underline">{p.name}</Link><span className={`priority p-${p.priority}`}>▴ {p.priority}</span><span><Avatar size="xs" name="Dexter"/></span><span>{p.dueDate?new Date(p.dueDate).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—'}</span><MoreHorizontal size={13} className="muted"/></div>)}<button className="add-inline list-add">+ Add Projects</button></div></div></div></main></div>}
